### PR TITLE
Add favicon on the website

### LINKED ISSUE #6998: Missing favicon on the website
Hi Marijn. I noticed that there is missing the favicon on the v5 website. Can I make a pull request?

### PR DESCRIPTION
**Pull request by jdbruxelles**
Closes #6998

### CODE REVIEW

**Comment by marijnh** [comment]
Oh, right, you'd have to change every single HTML file. I've added a redirect to my server config instead.

**Comment by jdbruxelles** [comment]
I think I don't have access to the server or its code. How did you do that (even if the server is not accessible to me), please?

**Comment by marijnh** [comment]
I added a redirect line to my Nginx config. And no, that's not something you could have done.

**Comment by jdbruxelles** [comment]
I'm just trying to understand what you did...
Ok for the `301` redirection, but how do you add the favicon without the `link` tag? It seems to me that you have not done so.

If I understand well, as long as there is a physical icon (or by redirection) at the `/favicon.ico` location, the `link` tag in the html is not mandatory because browsers try to retrieve `/favicon.ico`, even without having defined it in the html?

**Comment by marijnh** [comment]
Right, I made a forward from /favicon.ico, and since the browser fetches that anyway, even without link tag, it finds the icon.

**Comment by jdbruxelles** [comment]
Good point! Thank you 🤗.

**Pull request closed without merging**
