### PR TITLE
Cm6 vim

### PR DESCRIPTION
**Pull request by nightwing**
This pull request brings into sync vim.js and vim_test.js files in https://github.com/replit/codemirror-vim/pull/33 and here.
The only difference is the es module vs amd wrapper.

This will allow to use the same code both in cm5 and cm6 https://github.com/replit/codemirror-vim/tree/cm5/dev/cm5 and [demo.html](https://raw.githack.com/replit/codemirror-vim/cm5/dev/cm5/demo.html). But i am not sure how to modify the rollup script here to use vim code from npm package.

### CODE REVIEW

**Comment by marijnh** [comment]
Is this file from codemirror-vim available on npm? If so, I'd prefer to add that as a dependency and have a build script just copy it over, instead of having an endless series of pull requests to re-sync the files in the future.

**Comment by nightwing** [comment]
Would this work https://unpkg.com/browse/cm5-vim@0.0.1/?

**Comment by marijnh** [comment]
Yes, something like that should work. How is cm5-vim built? Directly from src/vim.js in codemirror-vim? Is that package provided specifically for this problem, or did it exist before?

Performing side effects in a rollup config file seems somewhat dodgy. Maybe we could use something like https://www.npmjs.com/package/rollup-plugin-copy instead?

**Comment by nightwing** [comment]
It is generated by https://github.com/replit/codemirror-vim/blob/cm5/dev/cm5/bin/build.js using src/vim.js and https://github.com/replit/codemirror-vim/blob/cm5/dev/cm5/index.js. My intention is to change the index.js to add a wrapper there too, so that we can move some of cm5 only code there.

If this is accepted i'll change the publish script of codemirror-vim to publish cm5-vim too with the main repository.

Probably it would have been better to include this in codemirror-vim itself, but that conflicts with [peerDependencies](https://github.com/replit/codemirror-vim/blob/5604d56098fa089de42befa786d747ac839d506d/package.json#L26-L32) field.

rollup-plugin-copy is indeed a better solution, i'll use that.

**Comment by marijnh** [comment]
One more thing—is there a pressing reason for keeping the vim tests in this package's test suite? I assume those are being ran as part of the codemirror-vim development process, and dropping them would make codemirror's test suite a lot more lightweight.

**Comment by nightwing** [comment]
Indeed, there is no important reason to keep them here too.

**Comment by marijnh** [comment]
Thank you!

I will go ahead and close all vim-related issues on this repository. Did you go through those to see which ones should be copied to codemirror-vim?

**Comment by nightwing** [comment]
I've checked only some of them, but closing is fine, because it won't destroy any information since issues can be searched using closing date.

**Pull request merged**
