### PR TITLE
Inline CSS Highlight Patch

### PR DESCRIPTION
**Pull request by dev-talha-akbar**
Introduces an option inlineCssMode which when set to true enable highlighting of CSS in the style attribute. Can be extended to highlight JavaScript in attributes such as onclick, onmouseup e.t.c.

### CODE REVIEW

**Comment by marijnh** [comment]
Hi. You're messing with the indentation and semicolons of lines that aren't affected by your patch. Please don't do that. Also please try to follow the coding style of the surrounding code with regards to spaces after `if`, not putting `else` on a new line, etc.

What is `isDefault` for? And why are you setting `inTag`, which so far is either a string or null, to `true` there?

**Comment by dev-talha-akbar** [comment]
Ah, sorry for the code indentation e.t.c.

If we are in any HTML tag,
set `isDefault` to `false`, set `inTag` to `true`.

`isDefault` is boolean & `false` because, I want to run my added behavior which further checks the attributes for a specific attribute and switch the mode.
`inTag` is boolean because, I don't wanna know what tag it is (we need any truth value).

If we are in an HTML tag but it is that specific tag which was provided in `tags` option from CodeMirror instance,
set `isDefault` to `true`, set `inTag` to the tag we're in (a string, again, truth value, valuable for conditions)

`isDefault `is boolean & `true` because, this time, we will run the code that was originally written by you to switch mode.

`inTag` is a `string` so, we can find associated mode to switch to from `tags` option.

I came across this problem for Codemirror because where I work at, the developers used to work alot in the style attribute tweaking styles. I thought it might help. I ain't good and it's posted so, someone can improve on this and integrate it into CM.

**Comment by phuongkt** [comment]
.

**Comment by marijnh** [comment]
Hey @phuongkt, stop adding empty reviews or I'll have to block you from the project.

**Comment by StellarDoor5319** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[mode/htmlmixed/htmlmixed.js, line 79 at r1](https://reviewable.io:443/reviews/codemirror/codemirror/4646#-KuDcCBPUOnyvYuuWKX-:-KuDcCBQfRVOH9fC3ZR9:b-yctxz) ([raw file](https://github.com/codemirror/codemirror/blob/c96aae3d946b3f8f78167e3ec8f22976f426a9ce/mode/htmlmixed/htmlmixed.js#L79)):*
> ```JavaScript
>       multilineTagIndentPastTag: parserConfig.multilineTagIndentPastTag
>     });
> ```

Why has this blank line been removed?  I think it makes the code easier to read.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/codemirror/codemirror/4646)*

**Comment by StellarDoor5319** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[mode/htmlmixed/htmlmixed.js, line 137 at r1](https://reviewable.io:443/reviews/codemirror/codemirror/4646#-KuL8qXxdSXRZtceskJ5:-KuL8qXxdSXRZtceskJ6:b-wrgpqy) ([raw file](https://github.com/codemirror/codemirror/blob/4969555bb637fa1327ce3501a2cce2ef767ab1f7/mode/htmlmixed/htmlmixed.js#L137)):*
> ```JavaScript
>       }
>       else if (state.isDefault && state.inTag && tag && />$/.test(stream.current())) {
>           var inTag = /^([\S]+) (.*)/.exec(state.inTag);
> ```

BTW these few lines have the incorrect indent.

---

*[mode/htmlmixed/htmlmixed.js, line 140 at r1](https://reviewable.io:443/reviews/codemirror/codemirror/4646#-KuL903VNWRV3gZazN1h:-KuL903WiZGMaqArqNj_:b-httzj7) ([raw file](https://github.com/codemirror/codemirror/blob/4969555bb637fa1327ce3501a2cce2ef767ab1f7/mode/htmlmixed/htmlmixed.js#L140)):*
> ```JavaScript
>           state.inTag = null;
>           state.isDefault = null;
>           var modeSpec = stream.current() == ">" && findMatchingMode(tags[inTag[1]], inTag[2])
> ```

BTW these three lines are indented incorrectly too

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/codemirror/codemirror/4646)*

**Pull request closed without merging**
